CREATE TABLE IF NOT EXISTS pinglist (
  Username TEXT PRIMARY KEY,
  Added INT
);

CREATE TABLE IF NOT EXISTS suggestions (
  Username TEXT PRIMARY KEY,
  Suggestion TEXT,
  Created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
